version: '3.8'

services:
  db:
    build: ./database
    container_name: turnero_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "1ng3n13r@s&st3m@s"
      MYSQL_DATABASE: turnero_db
      MYSQL_USER: turnero_user
      MYSQL_PASSWORD: "1ng3n13r@s&st3m@s"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - turnero_net

  backend:
    build: ./backend
    image: turnero_backend_img:v4
    container_name: turnero_backend
    restart: always
    ports:
      - "8100:8000"
    depends_on:
      - db
    networks:
      - turnero_net

  frontend:
    build: ./frontend
    image: turnero_frontend_img:v5
    container_name: turnero_frontend
    restart: always
    ports:
      - "8090:80"
    depends_on:
      - backend
    networks:
      - turnero_net

volumes:
  db_data:

networks:
  turnero_net:
